# File: .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    # Test across Linux, macOS, and Windows
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.10, 3.11]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-qt pytest-mock flake8 black

      - name: Lint with flake8
        run: flake8 src tests || true

      - name: Check code formatting with Black
        run: black --check . || true

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

  package:
    # Only build on Linux and Windows (macOS builds .app separately if desired)
    needs: build_and_test
    runs-on: ${{ matrix.os }}
    if: github.ref == 'refs/heads/main' && matrix.os != 'macos-latest'
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build standalone executable
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            pyinstaller --name ModularBacktester --onefile \
                       --add-data "templates:templates" \
                       --add-data "assets:assets" \
                       src/gui/main_window.py
          else
            pyinstaller --name ModularBacktester.exe --onefile --windowed \
                       --add-data "templates;templates" \
                       --add-data "assets;assets" \
                       src/gui/main_window.py
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ModularBacktester-${{ matrix.os }}
          path: dist/
          retention-days: 7
